### ISSUE TITLE
Reconciliate from VIAF 

### ISSUE THREAD

**Issue by silviaegt** [mcarruthers/LCNAF-Named-Entity-Reconciliation#2]
Dear Matt, thank you so much for your reconciliation services, I was wondering if there was a way of retrieving LCNAF headings when you already have the VIAF number. I am guessing I should change line [71](https://github.com/mcarruthers/LCNAF-Named-Entity-Reconciliation/blob/master/PersonalNamesReconcile.txt#L71) & [79](https://github.com/mcarruthers/LCNAF-Named-Entity-Reconciliation/blob/master/PersonalNamesReconcile.txt#L79) to something like: 
```
 "urlExpression": "grel:\"http://viaf.org/viaf/" + value,
```

but maybe I need to change line [64](https://github.com/mcarruthers/LCNAF-Named-Entity-Reconciliation/blob/master/PersonalNamesReconcile.txt#L64) as well? 
```
 "expression": "grel:replace(value, ' ', '%20')",
```

I am super newbie, so I'm not sure what that line does :s so any advice would be highly appreciated. 

Thank you again for making your work available online :)

**Comment by mcarruthers** [comment]
Hi Silvia,

I think what you suggested for lines 71 and 79 should work if you already have the VIAF number.  I don't think you would necessarily need to change line 64, since that command is looking to change whitespace into the corresponding hex code (%20).  Since the VIAF number shouldn't contain any whitespace, it won't make a difference.

If you have any other questions or run into any problems making your changes, please let me know and I would be happy to help.

Matt

**Comment by silviaegt** [comment]
That's so nice from you! Unfortunately after committing the changes (in lines 71 & 79, and changing the source column name to VIAF) I got an invalid JSON :( 
You can see my "adapted" version [here](https://github.com/silviaegt/LCNAF-Named-Entity-Reconciliation/blob/silviaegt-patch-1/VIAFReconcile.txt) and here you will find a (csv)[https://github.com/silviaegt/dh-toolbox/blob/master/viaf-test.csv] with some VIAFs for testing
PS I'm new to github and didn't really now how to do the whole "pull request" thing but I tried my best.

**Comment by mcarruthers** [comment]
Hi Sylvia,

I was able to fix the error in the JSON, and I also had to make a couple additional changes for the script to work, but you should be able to find the working copy [here](https://github.com/mcarruthers/testbed/blob/master/LCNAFReconciliationVIAFNumber.txt).  Also, when you upload your CSV file into Google Refine, make sure you uncheck the box that says "Parse cell text into numbers, dates...".  If you have any other questions, please feel free to ask.

**Comment by silviaegt** [comment]
Matt it works flawlessly!
Thank you so much!
