### ISSUE TITLE
Process stalls at "transpose columns into 2 cells"

### ISSUE THREAD

**Issue by lisagregory** [mcarruthers/LCNAF-Named-Entity-Reconciliation#3]
Hi Matt,

Thanks for posting such clear instructions for this process. I've tried to implement it a couple of times (attempting corporate, generic, and personal) but each one stalls at "transpose cells in 2 column(s)." 

The spreadsheet I'm working with is a single column list of names. It's got 713 rows, so it's not terribly large. I'm not new to Open Refine but I am new to something beyond its native functions. Do you have any ideas what might be happening? I'm happy to provide more information.

Thanks for your time.

Lisa Gregory

**Comment by mcarruthers** [comment]
Hi Lisa,

I'm not sure why you are getting a command that says "transpose cells into 2 column(s)".  It is a valid command in Google Refine, but it isn't included in any of my scripts.  Could you tell me what version of Google Refine you are using?

Matt

**Comment by lisagregory** [comment]
Hi Matt,

Sure thing. I've got Version 2.5 [r2407].

I found it in line 364 of GenericNamesReconcile.txt? If I'm looking in the
right place?

Thanks for getting back to me.

Lisa

**Comment by mcarruthers** [comment]
Hi Lisa,

That command should only apply to the GenericNamesReconcile.txt file, so I'm not sure why you would be seeing that command for the personal and corporate name scripts as well.  If the process is stalling no matter which file you run, it might have something to do with the spreadsheet you are using.  Would you be able to send me a copy of the spreadsheet [mcarruth at umich dot edu]?  That might help me troubleshoot what's happening.
